services:
  - type: web
    name: mon-app-devops
    runtime: image
    image:
      url: jordan237/mon-projet-devops:latest
    envVars:
      - key: ENV
        value: PRODUCTION
      - key: DB_HOST
        fromService:
          name: postgresql
          property: host
      - key: DB_NAME
        fromService:
          name: postgresql
          property: database
      - key: DB_USER
        fromService:
          name: postgresql
          property: user
      - key: DB_PASS
        fromService:
          name: postgresql
          property: password

  - type: postgres
    name: postgresql
    plan: free
    databaseName: monappdb
    user: admin